"""create core schema

Revision ID: 4e68505bb0d7
Revises: 52903a89f6e2
Create Date: 2026-07-11 10:52:15.639290

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4e68505bb0d7'
down_revision: str | None = '52903a89f6e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_ts', ['actor', 'ts'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('limit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('soft_pct', sa.Integer(), nullable=False),
    sa.Column('hard_pct', sa.Integer(), nullable=False),
    sa.Column('spent', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('resets_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_scope_id'), ['scope_id'], unique=False)

    op.create_table('orgs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('data_region', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=32), nullable=False),
    sa.Column('guardrails', sa.JSON(), nullable=False),
    sa.Column('routing', sa.JSON(), nullable=False),
    sa.Column('caching', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_id', name='uq_policy_scope')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_scope_id'), ['scope_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=True),
    sa.Column('team_id', sa.String(length=32), nullable=True),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_org_ts', ['org_id', 'ts'], unique=False)
        batch_op.create_index('ix_usage_team_ts', ['team_id', 'ts'], unique=False)

    op.create_table('provider_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_org_id'), ['org_id'], unique=False)

    op.create_table('rate_cards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'model', 'unit', name='uq_ratecard')
    )
    with op.batch_alter_table('rate_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_cards_org_id'), ['org_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_budget', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_user_org_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('apps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apps_team_id'), ['team_id'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('model_deployments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('public_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('credential_id', sa.String(length=32), nullable=True),
    sa.Column('routing_tags', sa.JSON(), nullable=False),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('cost_overrides', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['provider_credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'public_name', name='uq_model_org_publicname')
    )
    with op.batch_alter_table('model_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_deployments_org_id'), ['org_id'], unique=False)

    op.create_table('virtual_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('hashed_key', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.String(length=32), nullable=True),
    sa.Column('allowed_models', sa.JSON(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_keys_hashed_key'), ['hashed_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_virtual_keys_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_keys_team_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_keys_hashed_key'))

    op.drop_table('virtual_keys')
    with op.batch_alter_table('model_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_deployments_org_id'))

    op.drop_table('model_deployments')
    op.drop_table('memberships')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_team_id'))

    op.drop_table('apps')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_org_id'))

    op.drop_table('teams')
    with op.batch_alter_table('rate_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_cards_org_id'))

    op.drop_table('rate_cards')
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_org_id'))

    op.drop_table('provider_credentials')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_team_ts')
        batch_op.drop_index('ix_usage_org_ts')

    op.drop_table('usage_records')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_scope_id'))

    op.drop_table('policies')
    op.drop_table('orgs')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_scope_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_actor_ts')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
