"""add model_deployments.api_base

Revision ID: 69c9fd4d9027
Revises: 4e68505bb0d7
Create Date: 2026-07-11 11:18:45.910632

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '69c9fd4d9027'
down_revision: str | None = '4e68505bb0d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_base', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_deployments', schema=None) as batch_op:
        batch_op.drop_column('api_base')

    # ### end Alembic commands ###
